### PR TITLE
fix the platform restriction error providing more educational guidance 

### LINKED ISSUE #3061: Confusing UX: func build/deploy platform restriction error lacks actionable guidance
## **Current behavior:**
When running `func deploy` or `func build` with the `--platform` flag but without the S2I builder, the command shows an error message that doesn't help users understand what to do:

```txt
rayyan@rayyan-seliya:/mnt/c/Users/RAYYAN/Desktop/func/myfunction$ func deploy --registry ghcr.io/user --platform linux/amd64
Error: only S2I builds currently support specifying platform
```

This forces users to:
1. Understand what S2I means (not explained)
2. Guess how to enable S2I builder
3. Not understand which builders support which features
4. Miss the alternative of removing the flag

## **Proposed improvement:**
Provide clear, educational guidance about platform support and builder capabilities:

```txt
Error: platform not supported by builder

The --platform flag is only supported with the S2I builder.

Try this:
  func build --registry <registry> --builder=s2i --platform linux/amd64

Or remove the --platform flag:
  func build --registry <registry>

Builder capabilities:
  s2i   Supports --platform (Source-to-Image)
  pack  Does not support --platform (uses default)
  host  Does not support --platform (uses host architecture)

For more options, run 'func build --help'
```

For `func deploy`:
```txt
Error: platform not supported by builder

The --platform flag is only supported with the S2I builder.

Try this:
  func deploy --registry <registry> --builder=s2i --platform linux/amd64

Or remove the --platform flag:
  func deploy --registry <registry>

Builder capabilities:
  s2i   Supports --platform (Source-to-Image)
  pack  Does not support --platform (uses default)
  host  Does not support --platform (uses host architecture)

For more options, run 'func deploy --help'
```

**Solution:**
Implement a 2-layer error system:
- **Layer 1** (Technical): Return `ErrPlatformNotSupported` from validation in `pkg/functions/errors.go`
- **Layer 2** (CLI): Catch the error in `cmd/build.go` and `cmd/deploy.go` and provide user-friendly guidance with examples

## **Expected Workflow:**
According to the official documentation, using platform-specific builds requires:
1. Use the S2I builder explicitly: `func build --builder=s2i --platform linux/amd64 --registry <registry>`
2. Or use the default behavior without platform specification: `func build --registry <registry>`

The improved error message guides users through the correct usage.

## **Why S2I Only?**
Different builders have different platform support capabilities:
- **S2I (Source-to-Image)**: Supports cross-platform builds via `--platform` flag for building container images targeting specific architectures
- **Pack (Buildpacks)**: Uses automatic platform detection and doesn't support explicit platform override
- **Host**: Builds for the host machine's architecture only, no cross-platform support

## **User Impact:**
- **Current**: Cryptic error → confusion → need to search documentation → time wasted
- **Improved**: Immediate understanding → clear alternatives → better developer experience → faster onboarding

### PR DESCRIPTION
**Pull request by RayyanSeliya**
# Changes

- :bug: Fix confusing UX when using --platform flag without S2I builder
- :broom: Implement 2-layer error system for platform restriction errors
- :gift: Add educational guidance about builder capabilities

/kind enhancement

Fixes #3061 

## **Solution:**
Implement a 2-layer error system 
- **Layer 1** (Technical): Return `ErrPlatformNotSupported` from validation in `pkg/functions/errors.go`
- **Layer 2** (CLI): Catch the error in `cmd/build.go` and `cmd/deploy.go` and wrap with user-friendly guidance

**Release Note**

```release-note
func build and func deploy commands now provide clearer, more educational error messages when the --platform flag is used without the S2I builder, with actionable guidance and builder capability explanations.
```

### CODE REVIEW

**Comment by RayyanSeliya** [comment]
ptal @gauron99  @lkingland  when you have some moments !

File: cmd/build.go [hunk 1]
```diff
@@ -162,6 +162,25 @@ func runBuild(cmd *cobra.Command, _ []string, newClient ClientFactory) (err erro
...
+Try this:
+  func build --registry <registry> --builder=s2i --platform linux/amd64
+
+Or remove the --platform flag:
+  func build --registry <registry>
+
+Builder capabilities:
+  s2i   Supports --platform (Source-to-Image)
+  pack  Does not support --platform (uses default)
+  host  Does not support --platform (uses host architecture)
```
Comment (gauron99) [inline cmd/build.go]: TBH I think we dont need this SO explicitly said. You are redundantly saying the same thing here. I would be in favor of removing this whole section and just keeping the previous and following lines

File: cmd/deploy.go [hunk 2]
```diff
@@ -281,6 +281,25 @@ For more detailed deployment options, run 'func deploy --help'`)
...
+Try this:
+  func deploy --registry <registry> --builder=s2i --platform linux/amd64
+
+Or remove the --platform flag:
+  func deploy --registry <registry>
+
+Builder capabilities:
+  s2i   Supports --platform (Source-to-Image)
+  pack  Does not support --platform (uses default)
+  host  Does not support --platform (uses host architecture)
```
Comment (gauron99) [inline cmd/deploy.go]: same as above

**Review by gauron99 — COMMENTED** [review]
added some comments here

**Comment by gauron99** [comment]
BTW we have fixed the previous unrelated issue so once you make changes (or close and re-open the PR) those tests should be passing, if unrelated

**Review by gauron99 — APPROVED** [review]
/lgtm
