### PR TITLE
Remember `--registry-insecure` setting on recurring runs

### LINKED ISSUE #3489: `--registry-insecure` not remembered on recurring runs of `func deploy`
When I deploy a function with an insecure registry via `--registry-insecure` it works on the initial run. But on consecutive runs it is not "remembered" anymore:

Initial run works:
```
$ func deploy --registry localhost:5001 --registry-insecure
Building function image
🙌 Function built: localhost:5001/func-go-hello-world:latest
Pushing function image to the registry "localhost:5001" using the "" user credentials
warning: error while checking pull secrets: Get "https://localhost:5001/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority; GET http://localhost:5001/v2/: unexpected status code 400 Bad Request: Client sent an HTTP request to an HTTPS server.

🎯 Creating Triggers on the cluster
✅ Function deployed in namespace "default" and exposed at URL: 
   http://func-go-hello-world.default.svc.cluster.local
```

Afterwards when only `func deploy` is used, it is not "remembered":
```
$  func deploy                                              
function up-to-date. Force rebuild with --build
Error: failed to get credentials: creating push check transport for localhost:5001 failed: Get "https://localhost:5001/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority; GET http://localhost:5001/v2/: unexpected status code 400 Bad Request: Client sent an HTTP request to an HTTPS server.
```

I think this is, because the option is not stored in the `func.yaml`:
```
specVersion: 0.36.0
name: func-go-hello-world
runtime: go
registry: localhost:5001
namespace: default
created: 2025-11-17T11:20:29.114748843+01:00
build:
  builder: pack
deploy:
  namespace: default
  image: localhost:5001/func-go-hello-world@sha256:cb0b6d0ffb1d025f90da6a1d46c908f8f3d4bf10ec8e9608f228474c2470c21d
```

Also not sure about the `unexpected status code 400 Bad Request: Client sent an HTTP request to an HTTPS server`, while I'd expect `--registry-insecure` should only skip the TLS verification according to its docs. But that's probably a different issue

### PR DESCRIPTION
**Pull request by creydr**
Fixes #3489 

# Changes

- :bug: Remember `--registry-insecure` setting on recurring runs

Hint: This also reverts da21fa29868238a34d301f5e439a6dfe726a4c27, because when we have the `RegistryInsecure` in the function, this can be simplified.

### CODE REVIEW

File: cmd/build_registry_insecure_test.go [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+		t.Fatal(err)
+	}
+
+	var (
+		builder = mock.NewBuilder()
+		pusher  = mock.NewPusher()
+	)
+
+	// Test 1: Initial state - registryInsecure should be false
+	t.Run("initial_state_is_false", func(t *testing.T) {
```
Comment (twoGiants) [inline cmd/build_registry_insecure_test.go]: nit

No need for underscore in `t.Run` name argument. Go will add those underscores by itself when the tests are executed.

Same for all the others below.

```suggestion
	t.Run("initial state is false", func(t *testing.T) {
```

File: pkg/functions/function.go [hunk 2]
```diff
@@ -81,6 +81,10 @@ type Function struct {
 	// [registry]/[user].
 	Registry string `yaml:"registry,omitempty"`
 
+	// RegistryInsecure defines it the TLS verification of the registry
```
Comment (twoGiants) [inline pkg/functions/function.go]: nit

```suggestion
	// RegistryInsecure defines if the TLS verification of the registry
```

File: schema/func_yaml-schema.json [hunk 3]
```diff
@@ -182,6 +182,10 @@
 					"type": "string",
 					"description": "Registry at which to store interstitial containers, in the form\n[registry]/[user]."
 				},
+				"registryInsecure": {
+					"type": "boolean",
+					"description": "RegistryInsecure defines it the TLS verification of the registry\nshould be skipped."
```
Comment (twoGiants) [inline schema/func_yaml-schema.json]: nit

```suggestion
					"description": "RegistryInsecure defines if the TLS verification of the registry\nshould be skipped."
```

**Review by twoGiants — APPROVED** [review]
This is really useful and it all looks good! 😸 👍 

I have only a few nits.

[edit]: Did you run `./hack/update-codegen.sh`?

/approve
/lgtm
/hold for other reviewers

File: pkg/config/config.go [hunk 4]
```diff
@@ -70,6 +71,15 @@ func (c Global) RegistryDefault() string {
 	}
 }
 
+// WarnRegistryInsecureChange checks if the registry has changed but
+// registryInsecure is still set to true, and prints a warning if so.
+// This helps users avoid accidentally skipping TLS verification on a new registry.
+func (c Global) WarnRegistryInsecureChange(w io.Writer, f fn.Function) {
```
Comment (twoGiants) [inline pkg/config/config.go]: Unit tests missing.

File: pkg/functions/client.go [hunk 5]
```diff
@@ -372,6 +373,14 @@ func WithRegistry(registry string) Option {
 	}
 }
 
+// WithRegistryInsecure sets if the TLS verification of the registry should
+// be skipped.
```
Comment (gauron99) [inline pkg/functions/client.go:377]:
```suggestion
// WithRegistryInsecure sets if the TLS verification of the registry should
// be skipped.
//
// NOTE: Unlike WithRegistry and other Options, which act as a fallback (function's value
// takes precedence when set), WithRegistryInsecure(true) WILL override the 
// function's value unconditionally -> bool has no "unset" (unlike string's ""),
// so we cannot distinguish "not configured" from "explicitly set to false".
// As a result:
// - WithRegistryInsecure(true)  → always sets f.RegistryInsecure = true
// - WithRegistryInsecure(false) → preserves the function's existing value
//
// NOTE-2: gauron99 - If we ever need to make this consistent with the rest of Options
// RegistryInsecure needs to become *bool in Function's struct & global.Config struct
// (nil == unset == empty value) and it would most likely require special use of
// cmd.Flags.Changed() and viper.IsSet() (non-standard for rest of commands) 
```

File: pkg/functions/client.go [hunk 6]
```diff
@@ -372,6 +373,14 @@ func WithRegistry(registry string) Option {
...
+func WithRegistryInsecure(insecure bool) Option {
```
Comment (twoGiants) [inline pkg/functions/client.go:391]: Should we add a comment here, that  a `WithRegistryInsecure(false)` does not override function's existing `true`? Because one could think that this setting would set `registryInsecure` definitely to `false`.

File: pkg/functions/client.go [hunk 7]
```diff
@@ -690,6 +699,11 @@ func (c *Client) Build(ctx context.Context, f Function, options ...BuildOption)
 		f.Registry = c.registry
 	}
 
+	if c.registryInsecure {
+		// only override it, when given via the client
```
Comment (gauron99) [inline pkg/functions/client.go]:
```suggestion
        // Unlike other With* functions (like WithRegistry) this takes bool.
        // Bool has no "empty value" (like "" for string) therefore we always
        // override if client's value is true. 
        // See WithRegistryInsecure definition comment for more info.
```

File: pkg/config/config.go [hunk 8]
```diff
@@ -138,6 +148,8 @@ func (c Global) Apply(f fn.Function) Global {
 	if f.Registry != "" {
 		c.Registry = f.Registry
 	}
+	c.RegistryInsecure = f.RegistryInsecure
```
Comment (gauron99) [inline pkg/config/config.go:143]:
```suggestion
    // Unconditional because bool has no "empty value". Works because
    // viper resolves the correct precedence via our defaulting.
	c.RegistryInsecure = f.RegistryInsecure
```

File: pkg/config/config.go [hunk 9]
```diff
@@ -156,6 +168,8 @@ func (c Global) Configure(f fn.Function) fn.Function {
 	if c.Registry != "" {
 		f.Registry = c.Registry
 	}
+	f.RegistryInsecure = c.RegistryInsecure
```
Comment (gauron99) [inline pkg/config/config.go:165]:
```suggestion
    // Unconditional because bool has no "empty value". Works because
    // viper resolves the correct precedence via our defaulting.
	f.RegistryInsecure = c.RegistryInsecure
```

File: cmd/build_registry_insecure_test.go (hunk 1 above)
Comment (creydr) [reply cmd/build_registry_insecure_test.go]: updated

File: pkg/functions/function.go (hunk 2 above)
Comment (creydr) [reply pkg/functions/function.go]: good catch. updated

File: schema/func_yaml-schema.json (hunk 3 above)
Comment (creydr) [reply schema/func_yaml-schema.json]: updated

File: pkg/config/config.go (hunk 4 above)
Comment (creydr) [reply pkg/config/config.go]: Added one

File: pkg/functions/client.go (hunk 6 above)
Comment (creydr) [reply pkg/functions/client.go:391]: I accepted the suggestion from @gauron99 in https://github.com/knative/func/pull/3490#discussion_r2930302974
